version: '2'

services:
  web:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    external_links:
      - openeventdatabase_backend_1:backend

networks:
  default:
    external:
      name: openeventdatabase_default